version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.2
    environment:
      - PIPENV_VENV_IN_PROJECT=1

    steps:
      - checkout

      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "Pipfile.lock" }}
            - v2-dependencies-

      - run:
          name: install dependencies
          command: |
            sudo pip install pipenv
            pipenv install --dev

      - save_cache:
          paths:
            - .venv
          key: v2-dependencies-{{ checksum "Pipfile.lock" }}

      - run:
          name: run tests
          command: |
            pipenv run test
            codecov

